[package]
name = "jandan_pic_bot"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
failure = "0.1"
regex = "0.2"
curl = "0.4"
tokio-curl = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
futures-await = "0.1"
tokio-core = "0.1"
telebot = { path = "./telebot" }
kuchiki = "0.5"
lazy_static = "0.2"
image = "0.19"
base64 = "0.9"
