[package]
name = "jandan_pic_bot"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
error-chain = "0.7"
regex = "0.1"
curl = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
tokio-core = "0.1"
telebot = "0.1"
select = {git = "https://github.com/utkarshkukreti/select.rs"}