name: Rust

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        #include:
        # Allow failures on nightly
        #- rust: nightly
        #  can-fail: true
    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install FFmpeg
      run: |
        sudo apt-get update -qq && sudo apt-get -y install \
          libavcodec-dev \
          libavdevice-dev \
          libavfilter-dev \
          libavformat-dev \
          libavutil-dev \
          libpostproc-dev \
          libswresample-dev \
          libswscale-dev
    - name: Run tests
      run: cargo test --verbose
      #continue-on-error: ${{ matrix.can-fail }}
